### ISSUE TITLE
Exporting Awards proposals

### ISSUE THREAD

**Issue by bouraqadi** [Lin777/ESUGConfRegistrationApp#72]
The CSV files contains only the two first columns

**Comment by Lin777** [comment]
By the moment this function only has enabled the name of the project  and who proposed it, do you prefer to export all fields?

**Comment by bouraqadi** [comment]
Yes please Evelyn.

BTW, it would be great to have the name of the submitter too. The email is important for getting in touch with people, but it is private. 
Only submitters names are meant for display on the web page.

Thanks.
Noury

**Comment by Lin777** [comment]
Of course, then I will make those modifications ASAP

**Comment by Lin777** [comment]
Now export like this:
![image](https://user-images.githubusercontent.com/15729309/63537302-6d301a00-c4e3-11e9-8768-3b47c596ae30.png)
Do you prefer that also add the email of the submitter? PR #72

**Comment by bouraqadi** [comment]
> On 22 Aug 2019, at 19:49, Evelyn Cusi Lopez <notifications@github.com> wrote:
> 
> Now export like this:
>  <https://user-images.githubusercontent.com/15729309/63537302-6d301a00-c4e3-11e9-8768-3b47c596ae30.png>
Excellent!

**Comment by Lin777** [comment]
Great, then I'll join the master.

**Comment by bouraqadi** [comment]
Did you add the email too?
